extends SceneTree


func _init() -> void:
	call_deferred("run")


func run() -> void:
	var state := root.get_node_or_null("WorkdayState")
	if state == null:
		state = load("res://scripts/autoload/workday_state.gd").new()
		state.name = "WorkdayState"
		root.add_child(state)
	state.reset_for_tests()
	var console = load("res://scripts/autoload/developer_console.gd").new()
	root.add_child(console)
	await process_frame
	assert(console.dev_button != null, "DEV button must be created")
	assert(console.root_control.mouse_filter == Control.MOUSE_FILTER_IGNORE, "closed developer console must not intercept game input")
	assert(console.scene_selector.item_count == 7, "scene selector must expose menu, workday selector, narrative and five development scenes")
	assert(console.scene_selector.get_item_metadata(0) == "res://scenes/main_menu.tscn", "main menu must be selectable")
	assert(console.scene_selector.get_item_metadata(5) == "res://scenes/evening_map.tscn", "evening map must be selectable")
	assert(console.level_selector.item_count >= 1, "level selector must expose CSV-configured levels")
	assert(console.credit_selector != null, "developer console must expose political credit controls")
	assert(console.ration_selector != null, "developer console must expose ration coupon controls")
	assert(console.glass_event_selector.item_count == 12, "developer console must expose every supported glasses demo event")
	assert(console.glass_event_selector.get_item_metadata(2) == "npc", "glasses selector must preserve stable event ids")
	assert(console.glass_event_selector.get_item_metadata(7) == "secretary_daybrief", "glasses selector must expose the new secretary protocol")
	assert(console.collision_button != null, "developer console must expose collision visualization")
	assert(console.story_marker_button != null, "developer console must expose the key story NPC trigger")
	assert(not console.story_markers_enabled, "story NPC markers must default to off")
	assert(console.interaction_overlay != null, "developer console must create the UI interaction overlay")
	assert(not console.get_tree().debug_collisions_hint, "collision visualization must default to off")
	console.toggle_console()
	assert(console.is_open and console.blocker.visible, "console must open")
	console.credit_selector.value = 25
	console.set_credit_from_selector()
	assert(state.political_credit == 25, "credit selector must set political credit")
	console.adjust_credit(-10)
	assert(state.political_credit == 15, "credit shortcuts must adjust political credit")
	console.execute_command("credit add 7")
	assert(state.political_credit == 22, "credit command must add political credit")
	console.execute_command("credit set -3")
	assert(state.political_credit == -3, "credit command must set political credit")
	assert(console.status_label.text.contains("Credit：-3"), "credit changes must refresh status")
	console.ration_selector.value = 30
	console.set_rations_from_selector()
	assert(state.balance == 30, "ration selector must set the real coupon balance")
	console.adjust_rations(-10)
	assert(state.balance == 20, "ration shortcuts must adjust the real coupon balance")
	console.execute_command("ration add 7")
	assert(state.balance == 27, "ration command must add coupons")
	console.execute_command("ration set -2")
	assert(state.balance == -2, "ration command must support debt-state testing")
	assert(console.status_label.text.contains("配给券：-2"), "ration changes must refresh status")
	console.fill_test_records("mixed")
	assert(state.records.size() == 3, "mixed preset must create three records")
	assert(state.manager.get_summary().approved == 2, "mixed preset must create two approvals")
	assert(state.manager.get_summary().rejected == 1, "mixed preset must create one rejection")
	console.day_selector.value = 12
	console._on_set_day()
	assert(state.day_number == 12, "day selector must update workday")
	console.execute_command("clear")
	console.execute_command("state")
	assert(console.status_label.text.contains("工作日：12"), "state command must report current day")
	assert(console.status_label.text.contains("Credit：-3"), "state command must report current credit")
	assert(console.status_label.text.contains("配给券：-2"), "state command must report current ration balance")
	console.toggle_collision_debug()
	assert(console.get_tree().debug_collisions_hint, "collision switch must enable runtime collision drawing")
	assert(console.interaction_overlay.visible, "collision switch must reveal Control and Rect2 interaction zones")
	assert(console.collision_button.text.contains("显示"), "collision switch must report its enabled state")
	console.toggle_collision_debug()
	assert(not console.get_tree().debug_collisions_hint, "collision switch must disable runtime collision drawing")
	console.execute_command("npc story on")
	assert(console.story_markers_enabled, "npc story on must enable the persistent developer trigger")
	assert(console.story_marker_button.text.contains("显示"), "story marker button must report the enabled state")
	console.execute_command("npc story off")
	assert(not console.story_markers_enabled, "npc story off must disable the developer trigger")
	console.toggle_console()
	assert(not console.is_open and not console.blocker.visible, "console must close")
	print("FORMOCRACY_DEVELOPER_CONSOLE_TEST_OK")
	quit(0)
